/*
Delphix API Gateway

Delphix API Gateway API

API version: 1.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ListSnaphotsResponse struct for ListSnaphotsResponse
type ListSnaphotsResponse struct {
	Items []Snapshot `json:"items,omitempty"`
	ResponseMetadata *PaginatedResponseMetadata `json:"response_metadata,omitempty"`
}

// NewListSnaphotsResponse instantiates a new ListSnaphotsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSnaphotsResponse() *ListSnaphotsResponse {
	this := ListSnaphotsResponse{}
	return &this
}

// NewListSnaphotsResponseWithDefaults instantiates a new ListSnaphotsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSnaphotsResponseWithDefaults() *ListSnaphotsResponse {
	this := ListSnaphotsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ListSnaphotsResponse) GetItems() []Snapshot {
	if o == nil || o.Items == nil {
		var ret []Snapshot
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSnaphotsResponse) GetItemsOk() ([]Snapshot, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ListSnaphotsResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Snapshot and assigns it to the Items field.
func (o *ListSnaphotsResponse) SetItems(v []Snapshot) {
	o.Items = v
}

// GetResponseMetadata returns the ResponseMetadata field value if set, zero value otherwise.
func (o *ListSnaphotsResponse) GetResponseMetadata() PaginatedResponseMetadata {
	if o == nil || o.ResponseMetadata == nil {
		var ret PaginatedResponseMetadata
		return ret
	}
	return *o.ResponseMetadata
}

// GetResponseMetadataOk returns a tuple with the ResponseMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSnaphotsResponse) GetResponseMetadataOk() (*PaginatedResponseMetadata, bool) {
	if o == nil || o.ResponseMetadata == nil {
		return nil, false
	}
	return o.ResponseMetadata, true
}

// HasResponseMetadata returns a boolean if a field has been set.
func (o *ListSnaphotsResponse) HasResponseMetadata() bool {
	if o != nil && o.ResponseMetadata != nil {
		return true
	}

	return false
}

// SetResponseMetadata gets a reference to the given PaginatedResponseMetadata and assigns it to the ResponseMetadata field.
func (o *ListSnaphotsResponse) SetResponseMetadata(v PaginatedResponseMetadata) {
	o.ResponseMetadata = &v
}

func (o ListSnaphotsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.ResponseMetadata != nil {
		toSerialize["response_metadata"] = o.ResponseMetadata
	}
	return json.Marshal(toSerialize)
}

type NullableListSnaphotsResponse struct {
	value *ListSnaphotsResponse
	isSet bool
}

func (v NullableListSnaphotsResponse) Get() *ListSnaphotsResponse {
	return v.value
}

func (v *NullableListSnaphotsResponse) Set(val *ListSnaphotsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListSnaphotsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListSnaphotsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSnaphotsResponse(val *ListSnaphotsResponse) *NullableListSnaphotsResponse {
	return &NullableListSnaphotsResponse{value: val, isSet: true}
}

func (v NullableListSnaphotsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSnaphotsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


