/*
Delphix API Gateway

Delphix API Gateway API

API version: 1.0
Contact: support@delphix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiClientCreateParameter struct for ApiClientCreateParameter
type ApiClientCreateParameter struct {
	// An optional logical name for the API client.
	Name *string `json:"name,omitempty"`
	// Whether an API key must be generated for this API client. This must be set if the API client will be used for API key based authentication, and unset otherwise.
	GenerateApiKey *bool `json:"generate_api_key,omitempty"`
	// The unique ID which is used to identity the identity of an API request. The web server (nginx) configuration must be configured so as to include the external ID as the value of the X_CLIENT_ID HTTP request header when requests are proxied. If this value isn't set, the application will automatically generate one. For OAuth2/JWT based authentication, this typically corresponds to a value extracted from the JWT, uniquely identifying the API client.
	ApiClientId *string `json:"api_client_id,omitempty"`
	IsAdmin *bool `json:"is_admin,omitempty"`
	// Mapping of engine ID to the engine User ID.
	EngineUsersMapping []EngineUserMapping `json:"engine_users_mapping,omitempty"`
}

// NewApiClientCreateParameter instantiates a new ApiClientCreateParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiClientCreateParameter() *ApiClientCreateParameter {
	this := ApiClientCreateParameter{}
	var generateApiKey bool = true
	this.GenerateApiKey = &generateApiKey
	var isAdmin bool = false
	this.IsAdmin = &isAdmin
	return &this
}

// NewApiClientCreateParameterWithDefaults instantiates a new ApiClientCreateParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiClientCreateParameterWithDefaults() *ApiClientCreateParameter {
	this := ApiClientCreateParameter{}
	var generateApiKey bool = true
	this.GenerateApiKey = &generateApiKey
	var isAdmin bool = false
	this.IsAdmin = &isAdmin
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiClientCreateParameter) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientCreateParameter) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiClientCreateParameter) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiClientCreateParameter) SetName(v string) {
	o.Name = &v
}

// GetGenerateApiKey returns the GenerateApiKey field value if set, zero value otherwise.
func (o *ApiClientCreateParameter) GetGenerateApiKey() bool {
	if o == nil || o.GenerateApiKey == nil {
		var ret bool
		return ret
	}
	return *o.GenerateApiKey
}

// GetGenerateApiKeyOk returns a tuple with the GenerateApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientCreateParameter) GetGenerateApiKeyOk() (*bool, bool) {
	if o == nil || o.GenerateApiKey == nil {
		return nil, false
	}
	return o.GenerateApiKey, true
}

// HasGenerateApiKey returns a boolean if a field has been set.
func (o *ApiClientCreateParameter) HasGenerateApiKey() bool {
	if o != nil && o.GenerateApiKey != nil {
		return true
	}

	return false
}

// SetGenerateApiKey gets a reference to the given bool and assigns it to the GenerateApiKey field.
func (o *ApiClientCreateParameter) SetGenerateApiKey(v bool) {
	o.GenerateApiKey = &v
}

// GetApiClientId returns the ApiClientId field value if set, zero value otherwise.
func (o *ApiClientCreateParameter) GetApiClientId() string {
	if o == nil || o.ApiClientId == nil {
		var ret string
		return ret
	}
	return *o.ApiClientId
}

// GetApiClientIdOk returns a tuple with the ApiClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientCreateParameter) GetApiClientIdOk() (*string, bool) {
	if o == nil || o.ApiClientId == nil {
		return nil, false
	}
	return o.ApiClientId, true
}

// HasApiClientId returns a boolean if a field has been set.
func (o *ApiClientCreateParameter) HasApiClientId() bool {
	if o != nil && o.ApiClientId != nil {
		return true
	}

	return false
}

// SetApiClientId gets a reference to the given string and assigns it to the ApiClientId field.
func (o *ApiClientCreateParameter) SetApiClientId(v string) {
	o.ApiClientId = &v
}

// GetIsAdmin returns the IsAdmin field value if set, zero value otherwise.
func (o *ApiClientCreateParameter) GetIsAdmin() bool {
	if o == nil || o.IsAdmin == nil {
		var ret bool
		return ret
	}
	return *o.IsAdmin
}

// GetIsAdminOk returns a tuple with the IsAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientCreateParameter) GetIsAdminOk() (*bool, bool) {
	if o == nil || o.IsAdmin == nil {
		return nil, false
	}
	return o.IsAdmin, true
}

// HasIsAdmin returns a boolean if a field has been set.
func (o *ApiClientCreateParameter) HasIsAdmin() bool {
	if o != nil && o.IsAdmin != nil {
		return true
	}

	return false
}

// SetIsAdmin gets a reference to the given bool and assigns it to the IsAdmin field.
func (o *ApiClientCreateParameter) SetIsAdmin(v bool) {
	o.IsAdmin = &v
}

// GetEngineUsersMapping returns the EngineUsersMapping field value if set, zero value otherwise.
func (o *ApiClientCreateParameter) GetEngineUsersMapping() []EngineUserMapping {
	if o == nil || o.EngineUsersMapping == nil {
		var ret []EngineUserMapping
		return ret
	}
	return o.EngineUsersMapping
}

// GetEngineUsersMappingOk returns a tuple with the EngineUsersMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientCreateParameter) GetEngineUsersMappingOk() ([]EngineUserMapping, bool) {
	if o == nil || o.EngineUsersMapping == nil {
		return nil, false
	}
	return o.EngineUsersMapping, true
}

// HasEngineUsersMapping returns a boolean if a field has been set.
func (o *ApiClientCreateParameter) HasEngineUsersMapping() bool {
	if o != nil && o.EngineUsersMapping != nil {
		return true
	}

	return false
}

// SetEngineUsersMapping gets a reference to the given []EngineUserMapping and assigns it to the EngineUsersMapping field.
func (o *ApiClientCreateParameter) SetEngineUsersMapping(v []EngineUserMapping) {
	o.EngineUsersMapping = v
}

func (o ApiClientCreateParameter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.GenerateApiKey != nil {
		toSerialize["generate_api_key"] = o.GenerateApiKey
	}
	if o.ApiClientId != nil {
		toSerialize["api_client_id"] = o.ApiClientId
	}
	if o.IsAdmin != nil {
		toSerialize["is_admin"] = o.IsAdmin
	}
	if o.EngineUsersMapping != nil {
		toSerialize["engine_users_mapping"] = o.EngineUsersMapping
	}
	return json.Marshal(toSerialize)
}

type NullableApiClientCreateParameter struct {
	value *ApiClientCreateParameter
	isSet bool
}

func (v NullableApiClientCreateParameter) Get() *ApiClientCreateParameter {
	return v.value
}

func (v *NullableApiClientCreateParameter) Set(val *ApiClientCreateParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableApiClientCreateParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableApiClientCreateParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiClientCreateParameter(val *ApiClientCreateParameter) *NullableApiClientCreateParameter {
	return &NullableApiClientCreateParameter{value: val, isSet: true}
}

func (v NullableApiClientCreateParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiClientCreateParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


