/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiClient struct {
	// The entity ID of this API client.
	Id int64 `json:"id,omitempty"`
	// The unique ID which is used to identity the identity of an API request. The web server (nginx) configuration must be configured so as to include the external ID as the value of the X_CLIENT_ID HTTP request header when requests are proxied. For OAuth2/JWT based authentication, this typically corresponds to a value extracted from the JWT, uniquely identifying the API client.
	ApiClientId string `json:"api_client_id,omitempty"`
	Name string `json:"name,omitempty"`
	IsAdmin bool `json:"is_admin"`
	// Mapping of engine ID to the engine User ID.
	EngineUsersMapping []EngineUserMapping `json:"engine_users_mapping,omitempty"`
}
