/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// The Delphix storage-based copy of the source databse including its history.
type DSource struct {
	// The dSource object entity ID.
	Id string `json:"id,omitempty"`
	// The database type of this dSource.
	DatabaseType string `json:"database_type,omitempty"`
	// The container name of this dSource.
	Name string `json:"name,omitempty"`
	// The database version of this dSource.
	DatabaseVersion string `json:"database_version,omitempty"`
	// A universal ID that uniquely identifies the dSource database.
	DataUuid string `json:"data_uuid,omitempty"`
	// The actual space used by this dSource, in bytes.
	StorageSize int64 `json:"storage_size,omitempty"`
	// The version of the plugin associated with this source database.
	PluginVersion string `json:"plugin_version,omitempty"`
	// The date this dSource was created.
	CreationDate time.Time `json:"creation_date,omitempty"`
	// The name of the group containing this dSource.
	GroupName string `json:"group_name,omitempty"`
	// A value indicating whether this dSource is enabled.
	Enabled bool `json:"enabled,omitempty"`
	// A reference to the Engine that this dSource belongs to.
	EngineId string `json:"engine_id,omitempty"`
	// A reference to the Source associated with this dSource.
	SourceId string `json:"source_id,omitempty"`
	// The runtime status of the dSource. 'Unknown' if all attempts to connect to the source failed.
	Status string `json:"status,omitempty"`
}
