/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EngineUserMapping struct {
	EngineId int64 `json:"engine_id"`
	EngineUserId int64 `json:"engine_user_id"`
}
