/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Parameters to delete a VDB.
type DeleteVdbParameters struct {
	// Whether to continue the operation upon failures.
	Force bool `json:"force,omitempty"`
}
