/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Configuration required to connect and authenticate with an Hashicorp Vault which stores engines username and passwords.
type HashicorpVault struct {
	Id int64 `json:"id,omitempty"`
	// Environment variables to set when invoking the Vault CLI tool. The environment variables will be used both to login to the vault (if this step is required) and to retrieve engine username and passwords. 
	EnvVariables map[string]string `json:"env_variables,omitempty"`
	// Arguments to the \"vault\" CLI tool to be used to fetch a client token (or \"login\"). If supporting files, such as TLS certificates, must be used to authenticate, they can be mounted to the /etc/config directory. This property must not be set when using the TOKEN authentication method as login is not required. 
	LoginCommandArgs []string `json:"login_command_args,omitempty"`
}
