/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An asynchronous task.
type Job struct {
	// The Job entity ID.
	Id string `json:"id,omitempty"`
	// The status of the job.
	Status string `json:"status,omitempty"`
	// The type of job being done.
	Type_ string `json:"type,omitempty"`
	// Details about the failure for FAILED jobs.
	ErrorDetails string `json:"error_details,omitempty"`
}
