/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProvisionVdbResponse struct {
	// The ID of the provisioning job.
	JobId string `json:"job_id,omitempty"`
	Vdb *Vdb `json:"vdb,omitempty"`
}
