/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiClientCreateResponse struct {
	// The opaque token to use to authenticate for other API calls. The token must be included in all HTTP API calls in a request header named \"Authorization\", and prefixed with \"apk \" to denote that it is a proprietary API key format. For instance, if the token is \"abc123\", request must contain the following HTTP request header: \"Authorization: apk abc123\". 
	Token string `json:"token,omitempty"`
	ApiClientEntityId int64 `json:"api_client_entity_id,omitempty"`
}
