/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Parameters to disable a VDB.
type DisableVdbParameters struct {
	// Whether to attempt a cleanup of the VDB before the disable.
	AttemptCleanup bool `json:"attempt_cleanup,omitempty"`
}
