/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// A Data Control Tower object that references points in time for one or more datasets.
type Bookmark struct {
	// The Bookmark object entity ID.
	Id string `json:"id,omitempty"`
	// The user-defined name of this bookmark.
	Name string `json:"name"`
	// The date and time that this bookmark was created.
	CreationDate time.Time `json:"creation_date,omitempty"`
	// The list of VDB IDs associated with this bookmark.
	VdbIds []string `json:"vdb_ids"`
	// The retention policy for this bookmark, in days. A value of -1 indicates the bookmark should be kept forever.
	Retention int64 `json:"retention,omitempty"`
	// A message with details about operation progress or state of this bookmark.
	Status string `json:"status,omitempty"`
}
