/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The Delphix representation of the source database (not typically managed by Delphix).
type Source struct {
	// The Source object entity ID.
	Id string `json:"id,omitempty"`
	// The type of this source database.
	DatabaseType string `json:"database_type,omitempty"`
	// The name of this source database.
	Name string `json:"name,omitempty"`
	// The version of this source database.
	DatabaseVersion string `json:"database_version,omitempty"`
	// A reference to the Environment that hosts this source database.
	EnvironmentId string `json:"environment_id,omitempty"`
	// A universal ID that uniquely identifies this source database.
	DataUuid string `json:"data_uuid,omitempty"`
	// The IP address of the source's host.
	IpAddress string `json:"ip_address,omitempty"`
	// The FQDN of the source's host.
	Fqdn string `json:"fqdn,omitempty"`
	// The total size of this source database, in bytes.
	Size int64 `json:"size,omitempty"`
	// The JDBC connection URL for this source database.
	JdbcConnectionString string `json:"jdbc_connection_string,omitempty"`
	// The version of the plugin associated with this source database.
	PluginVersion string `json:"plugin_version,omitempty"`
}
