/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PaginatedResponseMetadata struct {
	// Pointer to the previous page of results. Use this value as a cursor query parameter in a subsequent request, along with limit, to navigate through the collection by virtual page.
	PrevCursor string `json:"prev_cursor,omitempty"`
	// Pointer to the next page of results. Use this value as a cursor query parameter in a subsequent request, along with limit, to navigate through the collection by virtual page.
	NextCursor string `json:"next_cursor,omitempty"`
	// The total number of results. This value may not be provided.
	Total int32 `json:"total,omitempty"`
}
