/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// A Delphix virtual database or dataset.
type Vdb struct {
	// The VDB object entity ID.
	Id string `json:"id,omitempty"`
	// The database type of this VDB.
	DatabaseType string `json:"database_type,omitempty"`
	// The container name of this VDB.
	Name string `json:"name,omitempty"`
	// The database version of this VDB.
	DatabaseVersion string `json:"database_version,omitempty"`
	// The total size of this VDB, in bytes.
	Size int64 `json:"size,omitempty"`
	// A reference to the Engine that this VDB belongs to.
	EngineId string `json:"engine_id,omitempty"`
	// The runtime status of the VDB. 'Unknown' if all attempts to connect to the dataset failed.
	Status string `json:"status,omitempty"`
	// A reference to the Environment that hosts this VDB.
	EnvironmentId string `json:"environment_id,omitempty"`
	// The IP address of the VDB's host.
	IpAddress string `json:"ip_address,omitempty"`
	// The FQDN of the VDB's host.
	Fqdn string `json:"fqdn,omitempty"`
	// A reference to the parent dataset of this VDB.
	ParentId string `json:"parent_id,omitempty"`
	// The name of the group containing this VDB.
	GroupName string `json:"group_name,omitempty"`
	// The date this VDB was created.
	CreationDate time.Time `json:"creation_date,omitempty"`
}
