/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Virtualization Engine Snapshot of a dSource or VDB.
type Snapshot struct {
	// The Snapshot ID.
	Id string `json:"id,omitempty"`
	// The logical time of the data contained in this Snapshot.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Database specific identifier for the data contained in this Snapshot, such as the Log Sequence Number (LSN) for MSsql databases, System Change Number (SCN) for Oracle databases.
	Location string `json:"location,omitempty"`
	// The ID of the Snapshot's dSource or VDB.
	DatasetId string `json:"dataset_id,omitempty"`
}
