/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A grouping of a single host or a cluster of hosts.
type Environment struct {
	// The Environment object entity ID.
	Id string `json:"id,omitempty"`
	// The name of this environment.
	Name string `json:"name,omitempty"`
	// The namespace of this environment for replicated and restored objects.
	Namespace string `json:"namespace,omitempty"`
	// A reference to the Engine that this Environment connection is associated with.
	EngineId int64 `json:"engine_id,omitempty"`
	// True if this environment is enabled.
	Enabled bool `json:"enabled,omitempty"`
	// True if this environment is a cluster of hosts.
	IsCluster bool `json:"is_cluster,omitempty"`
	// The hosts that are part of this environment.
	Hosts []Host `json:"hosts,omitempty"`
}
