/*
 * Delphix API Gateway
 *
 * Delphix API Gateway API
 *
 * API version: 1.0
 * Contact: support@delphix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Hook struct {
	Name string `json:"name,omitempty"`
	Command string `json:"command"`
	Shell string `json:"shell,omitempty"`
}
